### ISSUE TITLE
float4x4 multiplication is invalid

### ISSUE THREAD

**Issue by gabriele** [Unity-Technologies/Unity.Mathematics#16]
row by row mul instead of row by column

**Comment by runestubbe** [comment]
The matrix multiplication is correct, but there was some confusion about whether the matrix constructors were expecting row or column data. If you supply row data instead of column data your matrices are transposed and multiplying them will be as if you multiplied them in the wrong order, because B^T x A^T = (A x B)^T
We have renamed the constructor arguments to make it more explicit that the constructor arguments are in fact column, just like they the old Unity math library.
