### ISSUE TITLE
error CS1644: Feature 'using static' compiler error

### ISSUE THREAD

**Issue by willnode** [Unity-Technologies/Unity.Mathematics#19]
https://github.com/Unity-Technologies/Unity.Mathematics/blob/4e7541e7dbf7984046eea72aa5feab8751e45491/src/Unity.Mathematics/matrix.cs#L2

This forced my project to upgrade .NET to 4.5. But I think this is minor issue, anyway.

![image](https://user-images.githubusercontent.com/20214420/41697915-79c221a8-7545-11e8-90b9-3e567948bb58.png)

**Comment by xoofx** [comment]
Yes, Unity.Mathematics will require to be .NET 4.x+ at least (as ECS, burst...etc.). We can't express this constraint today via the Package Manager, but we expect to be able to do it at some point.

**Comment by RGiasingularity** [comment]
hi, please you help. I have to many projects in unity version 2018 and i was to upgrade at Unity 2019, but now all my projects in 2018, can´t be run and the mistake that show my is .."error CS1644: Feature `out variable declaration' cannot be used because it is not part of the C# 4.0 language specification
"......, please help because i don´t khnow what to do

**Comment by joncham** [comment]
@RGiasingularity please switch to the new scripting runtime in your project via the player settings.

**Comment by RGiasingularity** [comment]
> @RGiasingularity please switch to the new scripting runtime in your project via the player settings.

HI, thanks you very much for your answer, but a i dont understand, what have to change en the script?
