### ISSUE TITLE
Missing bool (bool1) type. 

### ISSUE THREAD

**Issue by AlexandreFiset** [Unity-Technologies/Unity.Mathematics#57]
The "bool" type disappear at some point while updating the package.

Is this desired? Boolean is quite convenient and since there are bool4 and etc. I don't see why we can't have bool1 :)

Cheers!

**Comment by xoofx** [comment]
`bool1` was only introduced at the beginning because we had some trouble getting proper codegen/marshalling to native memory, but it has been fixed since then, and so `bool1` is no longer required (same as we don't have a `float1` or a `int1`)

On the other hand, if you have an issue with `bool` not working with jobs, you can log an issue to [EntityComponentSystemSamples](https://github.com/Unity-Technologies/EntityComponentSystemSamples)

**Comment by AlexandreFiset** [comment]
> `bool1` was only introduced at the beginning because we had some trouble getting proper codegen/marshalling to native memory, but it has been fixed since then, and so `bool1` is no longer required (same as we don't have a `float1` or a `int1`)
> 
> On the other hand, if you have an issue with `bool` not working with jobs, you can log an issue to [EntityComponentSystemSamples](https://github.com/Unity-Technologies/EntityComponentSystemSamples)

Well if you happen to know anyone who can make C# blittable in Unity than it would be super helpful to poke them as this issue has been around for quite a while ([see](https://forum.unity.com/threads/bool1-gone-in-preview-4.532814/)). I'll open an issue in the other GitHub then, hoping to not have to hack my own version of a bool sometimes in the next five years.

**Comment by xoofx** [comment]
> Well if you happen to know anyone who can make C# blittable in Unity 

Well I know how to do it and I have been calling the team responsible for it to make the changes, but they haven't yet (they likely forgot). So keep asking them, they should be able to make it.
